FROM debian:oldstable@sha256:16fa2bfaac7ba5ea1dcc0d76fc05ecbb81cac13bd234f8be2d9befaded1e814e
LABEL maintainer="Sergey Makinen <sergey@makinen.ru>"

RUN apt-get update && \
  apt-get install --no-install-recommends -y ca-certificates git openssh-client unzip && \
  rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
  apt-get install --no-install-recommends -y build-essential clang llvm && \
  rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
  apt-get install --no-install-recommends -y curl xz-utils && \
  rm -rf /var/lib/apt/lists/* && \
  mkdir /usr/local/x86_64-unknown-freebsd && \
  cd /usr/local/x86_64-unknown-freebsd && \
  curl -L http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/amd64/14.2-RELEASE/base.txz | tar -Jxf - ./lib/ ./usr/lib/ ./usr/include/ && \
  cd usr/lib && \
  find . -xtype l | xargs ls -l | awk '{ system("ln -sf /usr/local/x86_64-unknown-freebsd" $11 " " $9) }'
